---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build datomic-pro nix package
        run: nix build .#datomic-pro
      - name: Run NixOS module tests
        run: nix flake check

  publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          name: Ramblurr/datomic-pro
          tag: "${{ inputs.tag }}"
